services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9030:9090"  # Prometheus web UI and API
    networks:
      grafana_labs:
        ipv4_address: 10.0.50.40
    volumes:
      - ${STORAGE_DIR}/:/mnt/data  # Prometheus storage
      - ${CONFIGS_DIR}/prometheus.yaml:/etc/prometheus/prometheus.yaml  # Shared config path
      - ${CERTS_DIR}/:/etc/certs  # Shared certs path
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    restart: unless-stopped

networks:
  grafana_labs:
    external: true
