services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"  # Loki HTTP API
    networks:
      grafana_labs:
        ipv4_address: 10.0.50.10
    volumes:
      - "${STORAGE_DIR}/:/mnt/data"  # Loki storage
      - "${CONFIGS_DIR}/loki-config.yaml:/etc/loki/loki-config.yaml"  # Shared config path
      - "${CERTS_DIR}/public.crt:/etc/public.crt:ro"
      - "${CERTS_DIR}/private.key:/etc/private.key:ro"
      - "${CERTS_DIR}/ca.crt:/etc/ca.crt:ro"
    extra_hosts:
      - "minio.${DOMAIN}:192.168.55.13" # MinIO backend
    environment:
      - "AWS_CA_BUNDLE=/etc/ca.crt"
    command: -config.expand-env=true -config.file=/etc/loki/loki-config.yaml
    restart: unless-stopped

networks:
  grafana_labs:
    external: true



