services:
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    networks:
      grafana_labs:
        ipv4_address: 10.0.50.30
    volumes:
      - ${STORAGE_DIR}/logs:/var/log  # Promtail logs
      - ${CONFIGS_DIR}/promtail-config.yaml:/etc/promtail/promtail-config.yaml  # Shared config path (corrected)
      - ${CERTS_DIR}/promtail:/etc/certs  # Shared certs path
      - ${STORAGE_DIR}/tmp:/tmp  # Persist positions.yaml file inside ${STORAGE_DIR}/tmp on the host
    command: -config.file=/etc/promtail/promtail-config.yaml
    restart: unless-stopped

networks:
  grafana_labs:
    external: true
