services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"  # Expose Redis default port
    networks:
      redis:
        ipv4_address: 10.0.80.2
    restart: unless-stopped

networks:
  redis:
    name: redis
    driver: bridge
    ipam:
      config:
        - subnet: "10.0.80.0/24"
